apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
  namespace: capstone-namespace
  labels:
    app: cloud-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
        - name: cloud-gateway-app
          image: 248155485793.dkr.ecr.us-east-1.amazonaws.com/cloud-gateway-repo:staging_1.0_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
  namespace: capstone-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9191
      protocol: TCP
  selector:
    app: cloud-gateway-app
