apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  namespace: capstone-namespace
  labels:
    app: department-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-app
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      containers:
        - name: department-service-app
          image: 248155485793.dkr.ecr.us-east-1.amazonaws.com/department-service-repo:staging_1.0_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
  namespace: capstone-namespace
spec:
  ports:
    - targetPort: 9001
      port: 80
  selector:
    app: department-service-app
