apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  namespace: capstone-namespace
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: 248155485793.dkr.ecr.us-east-1.amazonaws.com/user-service-repo:staging_1.0_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  namespace: capstone-namespace
spec:
  ports:
    - targetPort: 9002
      port: 80
  selector:
    app: user-service-app
